version: "3.9.5"
services:
  database:
    container_name: database
    restart: always
    image: postgres:12.7-alpine
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    volumes:
      - ./:/app
    depends_on:
      - database
    command: gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=2 config.wsgi

  nginxrp:
    container_name: nginxrp
    restart: always
    build: ./nginx-server
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - ./staticfiles:/staticfiles

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.9-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celeryworker:
    container_name: celeryworker
    build: .
    volumes:
      - ./:/backend
    command: celery -A config.celery worker --pool=prefork -l info
    depends_on:
      - rabbitmq

  celeryscheduler:
    container_name: celeryscheduler
    build: .
    volumes:
      - ./:/app
    command: celery -A config beat -l info
    depends_on:
      - celery

volumes:
  db_data:
  rabbitmq_data:

