# Generated by Django 4.2.10 on 2024-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
