# Generated by Django 4.2.10 on 2024-02-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='user',
        ),
        migrations.AddField(
            model_name='lessons',
            name='users',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
