# Generated by Django 4.2.10 on 2024-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_lessons_user_lessons_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='users',
        ),
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.CharField(default=2, max_length=300, verbose_name='Video nomi:'),
            preserve_default=False,
        ),
    ]
