# Generated by Django 4.2.10 on 2024-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=300, verbose_name="To'liq ism sharifi:")),
                ('bio', models.TextField()),
                ('job', models.CharField(max_length=200, verbose_name='Kasbi va yonalishi')),
            ],
            options={
                'verbose_name': 'Avtor haqida_',
            },
        ),
    ]
